#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_INSTALLER="${SCRIPT_DIR}/devworks-install.sh"
if [[ ! -x "${DEFAULT_INSTALLER}" && -x /opt/devworks/installer/devworks-install.sh ]]; then
  DEFAULT_INSTALLER="/opt/devworks/installer/devworks-install.sh"
fi
INSTALLER="${DEVWORKS_INSTALLER:-${DEFAULT_INSTALLER}}"
CONFIG_OUT="${DEVWORKS_WIZARD_CONFIG:-/tmp/devworks-install.env}"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

need_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run with sudo: sudo devworks-installer (or sudo bash /run/live/medium/devworks-installer from the current USB)"
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

is_yes_answer() {
  case "${1:-}" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

prompt_default() {
  local prompt="$1"
  local default="$2"
  local answer=""
  printf '%s [%s]: ' "${prompt}" "${default}"
  read -r answer
  printf '%s' "${answer:-${default}}"
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-no}"
  local answer=""
  local suffix="[y/N]"
  [[ "${default}" == "yes" ]] && suffix="[Y/n]"
  while true; do
    printf '%s %s: ' "${prompt}" "${suffix}"
    read -r answer
    answer="${answer:-${default}}"
    case "${answer}" in
      y|Y|yes|YES) return 0 ;;
      n|N|no|NO) return 1 ;;
      *) printf 'Please answer yes or no.\n' >&2 ;;
    esac
  done
}

validate_linux_username() {
  [[ "$1" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]
}

quote_value() {
  printf '%q' "$1"
}

disk_partitions() {
  local disk="$1"
  lsblk -o NAME,SIZE,TYPE,FSTYPE,PARTLABEL,LABEL,MOUNTPOINTS "${disk}" || true
}

live_disk_parent() {
  local source parent
  source="$(findmnt -n -o SOURCE /run/live/medium 2>/dev/null || true)"
  [[ -n "${source}" && -b "${source}" ]] || return 0
  parent="$(lsblk -no PKNAME "${source}" 2>/dev/null | head -n1 | xargs || true)"
  [[ -n "${parent}" ]] || return 0
  printf '/dev/%s' "${parent}"
}

load_disks() {
  mapfile -t DISKS < <(
    lsblk -dnpo PATH,TYPE | awk '$2 == "disk" {print $1}' |
      while read -r disk; do
        [[ -b "${disk}" ]] && printf '%s\n' "${disk}"
      done
  )
  [[ "${#DISKS[@]}" -gt 0 ]] || die "No target disks were found."
}

show_disk_table() {
  local live_parent="$1"
  printf '\nAvailable disks\n'
  printf '===============\n'
  printf '%-4s %-16s %-10s %-22s %-18s %s\n' "No" "Device" "Size" "Model" "Serial" "Note"
  local i=1
  local disk size model serial note
  for disk in "${DISKS[@]}"; do
    size="$(lsblk -dnpo SIZE "${disk}" | xargs || true)"
    model="$(lsblk -dnpo MODEL "${disk}" | sed 's/[[:space:]]\+/ /g' | xargs || true)"
    serial="$(lsblk -dnpo SERIAL "${disk}" | sed 's/[[:space:]]\+/ /g' | xargs || true)"
    note=""
    [[ "${disk}" == "${live_parent}" ]] && note="installer USB - blocked"
    if lsblk -nr -o FSTYPE,PARTLABEL,LABEL,MOUNTPOINTS "${disk}" | grep -Eiq 'ntfs|BitLocker|EFI|ESP|Microsoft|Windows'; then
      note="${note:+${note}; }existing OS/data detected"
    fi
    printf '%-4s %-16s %-10s %-22s %-18s %s\n' "${i}" "${disk}" "${size}" "${model:0:22}" "${serial:0:18}" "${note}"
    i=$((i + 1))
  done
}

select_disk() {
  local live_parent="$1"
  local choice disk
  while true; do
    show_disk_table "${live_parent}"
    printf '\nSelect target disk number to erase, or q to quit: '
    read -r choice
    [[ "${choice}" == "q" || "${choice}" == "Q" ]] && exit 0
    [[ "${choice}" =~ ^[0-9]+$ ]] || {
      printf 'Please enter a disk number.\n' >&2
      continue
    }
    (( choice >= 1 && choice <= ${#DISKS[@]} )) || {
      printf 'Disk number out of range.\n' >&2
      continue
    }
    disk="${DISKS[$((choice - 1))]}"
    if [[ -n "${live_parent}" && "${disk}" == "${live_parent}" ]]; then
      printf 'Refusing to install to the USB installer disk: %s\n' "${disk}" >&2
      continue
    fi
    TARGET_DISK="${disk}"
    return 0
  done
}

write_config() {
  local ssh_password_auth="$1"
  local ssh_key_mode="$2"
  local require_keys="$3"

  cat > "${CONFIG_OUT}" <<EOF
# Generated by Devworks Installer Wizard.
# This config intentionally installs a clean desktop/server base first.
DEVWORKS_I_UNDERSTAND_THIS_ERASES_DISK="no"
DEVWORKS_MANUAL_CONFIRM_DISK="yes"
DEVWORKS_ALLOW_INSTALL_ON_MOUNTED_DISK="no"
INSTALL_MODE="erase-disk"
TARGET_DISK="$(quote_value "${TARGET_DISK}")"
TARGET_BOOT_MODE="auto"
TARGET_SWAP_SIZE_MIB="4096"
APT_COMPONENTS="main contrib non-free non-free-firmware"
ENABLE_HARDWARE_BACKPORTS="no"

DEVWORKS_HOSTNAME="$(quote_value "${HOSTNAME_VALUE}")"
DEVWORKS_VERSION="0.2.1"
DEVWORKS_VERSION_NAME="Dual Boot Hardware"
TIMEZONE="Asia/Jakarta"
LOCALE="en_US.UTF-8"
KEYMAP="us"

ADMIN_USER="$(quote_value "${ADMIN_USER_VALUE}")"
ADMIN_FULL_NAME="Devworks Administrator"
ADMIN_PASSWORD_MODE="prompt"
ADMIN_PASSWORD_HASH=""
FORCE_PASSWORD_CHANGE="no"
ADMIN_SUDO_NOPASSWD="no"
ENABLE_AUTOLOGIN="no"

SSH_PORT="22"
SSH_PASSWORD_AUTH="${ssh_password_auth}"
SSH_PERMIT_ROOT_LOGIN="no"
SSH_ALLOW_USERS="\${ADMIN_USER}"
SSH_AUTHORIZED_KEYS_FILE=""
SSH_KEY_SETUP_MODE="${ssh_key_mode}"
REQUIRE_SSH_AUTHORIZED_KEYS="${require_keys}"
SSH_DISABLE_EMPTY_PASSWORDS="yes"
SSH_MAX_AUTH_TRIES="3"

ENABLE_UFW="yes"
ALLOW_HTTP="no"
ALLOW_HTTPS="no"
ALLOW_ADMIN_UI_PORT="no"
TLS_MODE="off"
TLS_DOMAIN="devworks.local"
TLS_CERT_SOURCE=""
TLS_KEY_SOURCE=""

ENABLE_WEB_STACK="no"
WEB_SERVICE_NAME="devworks-web"
WEB_ROOT="/srv/devworks/web"
WEB_ENABLE_FIREWALL="no"
WEB_TLS_MODE="off"
ENABLE_AI_RUNTIME="no"
AI_RUNTIME_MODE="none"
AI_BIND_ADDRESS="127.0.0.1"
AI_MEMORY_MAX="8G"
AI_CPU_QUOTA="300%"
AI_ENABLE_FIREWALL="no"
ENABLE_CONTAINER_RUNTIME="none"
INSTALL_WEB_FEATURE_PACKAGES="yes"
INSTALL_AI_FEATURE_PACKAGES="no"
INSTALL_CONTAINER_FEATURE_PACKAGES="no"
ENABLE_SERVICE_WIZARD="yes"

ENABLE_GUI="yes"
ENABLE_NATIVE_MONITOR="yes"
ENABLE_ADMIN_WEB_UI="no"
ADMIN_WEB_UI_BIND="127.0.0.1"

ENABLE_UNATTENDED_UPGRADES="yes"
ENABLE_AUTO_REBOOT_AFTER_SECURITY_UPDATE="no"
ENABLE_GRUB_RECOVERY="yes"
ENABLE_WINDOWS_BOOT_DETECTION="yes"
POST_INSTALL_REBOOT="no"
EOF
  chmod 0600 "${CONFIG_OUT}"
}

main() {
  need_root
  need_cmd lsblk
  need_cmd findmnt
  [[ -x "${INSTALLER}" ]] || die "Installer not found: ${INSTALLER}"

  clear || true
  cat <<'EOF'
Devworks Server OS Installer Wizard
===================================

This simple wizard installs Devworks OS to one whole disk.

WARNING:
  The selected disk will be erased completely.
  Windows, applications, and files on that disk will be removed.
  Web, AI, Docker, and public ports stay disabled after install.

EOF

  local live_parent=""
  live_parent="$(live_disk_parent || true)"
  load_disks
  select_disk "${live_parent}"

  printf '\nSelected target disk: %s\n\n' "${TARGET_DISK}"
  disk_partitions "${TARGET_DISK}"

  HOSTNAME_VALUE="$(prompt_default "Hostname" "devworks-server")"
  ADMIN_USER_VALUE="$(prompt_default "Admin username" "devworks")"
  validate_linux_username "${ADMIN_USER_VALUE}" || die "Invalid Linux username: ${ADMIN_USER_VALUE}"

  local ssh_password_auth="yes"
  local ssh_key_mode="prompt"
  local require_keys="no"
  if prompt_yes_no "Allow temporary SSH password login for first setup?" "yes"; then
    ssh_password_auth="yes"
    ssh_key_mode="prompt"
    require_keys="no"
  else
    ssh_password_auth="no"
    ssh_key_mode="required"
    require_keys="yes"
  fi

  cat <<EOF

Install summary
===============
Mode:              erase whole disk
Target disk:       ${TARGET_DISK}
Hostname:          ${HOSTNAME_VALUE}
Admin user:        ${ADMIN_USER_VALUE}
Desktop GUI:       enabled
Control Center:    native desktop app
SSH port:          22
SSH password auth: ${ssh_password_auth}
Web service:       disabled until user enables it
AI service:        disabled until user enables it
Container runtime: disabled until user enables it
Config file:       ${CONFIG_OUT}

EOF

  printf 'To continue, type exactly: ERASE %s\n' "${TARGET_DISK}"
  printf '> '
  local confirmation=""
  read -r confirmation
  [[ "${confirmation}" == "ERASE ${TARGET_DISK}" ]] || die "Confirmation did not match. Nothing was installed."

  write_config "${ssh_password_auth}" "${ssh_key_mode}" "${require_keys}"
  printf '\nConfig written to: %s\n' "${CONFIG_OUT}"
  printf 'Starting installer. You will be asked to create the admin password.\n\n'
  exec bash "${INSTALLER}" --config "${CONFIG_OUT}"
}

main "$@"
